# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 89d9c96a00d4b5b0b167bf34ad58858719b00cca7f7e4b49778c85377af636fcfd713e30308f976aabbc745649b9bc58a5439d5dc8346c8836a4aea66eaf79d6

test:
  secret_key_base: bdb7e667f64bc0aa0f7a447a7ebb7fa2c5c2badd90a101d2f2b867a28379c4e72708dd84e99db9077fedcd65841bdd90de4397a6e859fe1d4f36ba91308fe88a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
